version: "3.8"

services:

  db:
    image: projectkspacee1/myserver:dbimage
    ports:
      - "3306:3306"

  auth:
    image: projectkspacee1/myserver:authimage
    ports:
      - "5001:5001"

  book:
    image: projectkspacee1/myserver:bookimage
    ports:
      - "5002:5002"

  borrow:
    image: projectkspacee1/myserver:borrowimage
    ports:
      - "5003:5003"

  app:
    image: projectkspacee1/myserver:appimage
    ports:
      - "5000:5000"
