version: "3.9"

services:
  db:
    image: dbimage
    ports:
      - "3306:3306"

  auth_service:
    image: authimage
    ports:
      - "5001:5001"

  book_service:
    image: bookimage
    ports:
      - "5002:5002"

  borrow_service:
    image: borrowimage
    ports:
      - "5003:5003"

  frontend:
    image: frontimage
    ports:
      - "5000:5000"

