---
services:
  db:
    image: dbimage
    ports:
      - "3306:3306"
    networks:
      - flm_mynet

  auth_services:
    image: authimage
    ports:
      - "5001:5001"
    networks:
      - flm_mynet

  book_services:
    image: bookimage
    ports:
      - "5002:5002"
    networks:
      - flm_mynet

  borrow_services:
    image: borrowimage
    ports:
      - "5003:5003"
    networks:
      - flm_mynet

  frontend:
    image: frontimage
    ports:
      - "5000:5000"
    networks:
      - flm_mynet

networks:
  flm_mynet:
    driver: overlay
    
